(defvar git-directory "~/Git/")
(defvar secrets-file (concat user-emacs-directory "env/secrets.el"))
(defvar p-font-size "12")
(cond ((eq system-type 'gnu/linux)
       (defvar p-font (concat "FiraCode Nerd Font Mono-" p-font-size)))
      ((eq system-type 'windows-nt)
       (defvar p-font (concat "FiraCode NFM-" p-font-size)))
      (t (error "Wrong system type")))
